---
abstract: 'RT-Extension-ReplyWithMail Extension'
author:
  - 'Averkios'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: gpl_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-ReplyWithMail
no_index:
  directory:
    - html
    - inc
requires:
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/averkios/RT-Extension-ReplyWithMail
version: '0.02'
x_module_install_rtx_version: '0.42'
x_requires_rt: 4.4.0
x_rt_too_new: 5.2.0
